name: CD

on:
  workflow_dispatch:

permissions: read-all

jobs:
  deploy_dev:
    name: Preparing Alpha release
    if: ${{ github.repository == 'sws2apps/jw-epub-parser' && github.ref == 'refs/heads/alpha' }}
    environment:
      name: Development
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - name: Checkout for release preparation
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
        with:
          ref: alpha
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install package dependencies
        run: npm ci

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@3b88c82b34098e8b51e401c1082c9170b0a3ec3c
        with:
          semantic_version: 19.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  deploy_stg:
    name: Preparing Beta release
    if: ${{ github.repository == 'sws2apps/jw-epub-parser' && github.ref == 'refs/heads/beta' }}
    environment:
      name: Staging
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - name: Checkout for release preparation
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
        with:
          ref: beta
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install package dependencies
        run: npm ci

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@3b88c82b34098e8b51e401c1082c9170b0a3ec3c
        with:
          semantic_version: 19.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  deploy_prod:
    name: Preparing Production release
    if: ${{ github.repository == 'sws2apps/jw-epub-parser' && github.ref == 'refs/heads/main' }}
    environment:
      name: Production
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - name: Checkout for release preparation
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
        with:
          ref: main
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install package dependencies
        run: npm ci

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@3b88c82b34098e8b51e401c1082c9170b0a3ec3c
        with:
          semantic_version: 19.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
