name: PROD-to-STG

on:
  workflow_dispatch:

permissions: read-all

jobs:
  prod_to_dev:
    name: Rebase from production to staging
    if: ${{ github.repository == 'sws2apps/jw-epub-parser' && github.ref == 'refs/heads/main' }}
    environment:
      name: Staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout for rebase preparation
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Do git rebase
        run: |
          git fetch --all
          git rebase --onto origin/main beta
          git push -f origin beta
